### ISSUE TITLE
MacOS Brew install deprecated

### ISSUE THREAD

**Issue by nwOLXTYv** [outscale/frieza#337]
Hi !

I tried installing the tool using brew and there is the output :
<img width="763" alt="image" src="https://github.com/user-attachments/assets/841b2066-4d50-4ff0-869e-0932bbf2162a">

Is there any other way to install it using cli ?

**Comment by outscale-mgo** [comment]
Hello, it seems you didn't add outscale/tap to your brew repository.
To do so, you need to execute this command:
```
brew tap outscale/tap
```

Because you might not be the only one with this problem, we did improve the documentation in [this](https://github.com/outscale/frieza/commit/b788c0a09e5e72b9607929de5c98889ff71772d4) commit.

Thanks for reporting an issue, helping us to improve frieza.
